---
title: "rbokeh iris dataset"
author: "Ryan Hafen"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    source_code: embed
---

```{r setup, include=FALSE}
library(rbokeh)
library(flexdashboard)
library(viridisLite)
library(viridis)
```

row
-----------------------------------------------------------------------

### Species

```{r}
figure(width = NULL, height = NULL) %>%
    ly_points(Sepal.Length, Sepal.Width, data = iris, color = Species, glyph = Species,
    hover = list(Sepal.Length, Sepal.Width)) %>%
    set_palette(discrete_color = pal_color(c("seagreen", "yellowgreen", "springgreen")))

# figure() %>%
#   ly_points(Sepal.Length, Sepal.Width, data = iris,
#     color = Species, glyph = Species)
```


row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Species (Quantile)

```{r}
figure(width = NULL, height = NULL, legend_location = "top_left") %>%
  ly_quantile(Sepal.Length, group = Species, data = iris)
```

### Petal Width

```{r}
figure(width = NULL, height = NULL) %>%
  ly_points(Sepal.Length, Sepal.Width, data = iris,
    color = Petal.Width)
```